# Generated by Django 4.0.3 on 2022-03-26 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='post_image', verbose_name='Фото категории')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Подробнее')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарии')),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=255, verbose_name='форма')),
            ],
            options={
                'verbose_name': 'Форма',
                'verbose_name_plural': 'Форма',
                'ordering': ['forma'],
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото компании')),
                ('num', models.CharField(max_length=255, verbose_name='ИНН')),
                ('admin', models.CharField(max_length=255, verbose_name='Администратор')),
                ('country', models.CharField(max_length=255, verbose_name='Гражданин')),
                ('contact', models.CharField(max_length=255, verbose_name='Номер')),
                ('content', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.category', verbose_name='Категории')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.forma', verbose_name='форма')),
            ],
            options={
                'verbose_name': 'Компании',
                'verbose_name_plural': 'Компания',
                'ordering': ['licenses'],
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenses', models.CharField(max_length=255, verbose_name='Лицензи')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Лицензи',
                'verbose_name_plural': 'Лицензия',
                'ordering': ['licenses'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Название')),
                ('certificate', models.ImageField(upload_to='', verbose_name='Сертификат')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.info', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификат',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='info',
            name='licenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.licenses', verbose_name='Лицензи'),
        ),
    ]
